### ISSUE TITLE
oechem dependence

### ISSUE THREAD

**Issue by janweinreich** [binghuang2018/aqml#4]
i have set `export CHEMPACK=RDKIT` but i still get

```
 genamon -k 6 "Cc1ccccc1"                                                                                            
 -- now excuting /Users/jan/projects/aqml/bin/genamon -k 6 Cc1ccccc1
#Mid 1 Cc1ccccc1
LICENSE: Could not open license file "oe_license.txt" in local directory
LICENSE: N.B. OE_LICENSE environment variable is not set
LICENSE: N.B. OE_DIR environment variable is not set
LICENSE: No product keys!
LICENSE: No valid license found for oechem
```

**Comment by janweinreich** [comment]
What are the restrictions when working with rdkit versus openeye when using aqml?

**Comment by binghuang2018** [comment]
Hey @janweinreich! Essentially, there is no significant difference between the versions using RDKit and OEChem. However, OEChem is generally more robust and better equipped to handle complex cases, such as unusual bond patterns. If your work involves bio- and organic chemistry, you shouldn't encounter these issues.

**Comment by janweinreich** [comment]
hey @binghuang2018 ! i was following the installation instructions to use RDKIT but I still get

```
genamon -k 6 "ccccc"                                                                                                                 
 -- now excuting /Users/jan/projects/aqml/bin/genamon -k 6 ccccc
#Mid 1 ccccc
LICENSE: Could not open license file specified by OE_LICENSE environment variable "/path/to/oe_license.txt"
LICENSE: Could not open license file "oe_license.txt" in local directory
LICENSE: N.B. OE_DIR environment variable is not set
LICENSE: No product keys!
LICENSE: No valid license found for oechem
```

and no amons are generated

**Comment by janweinreich** [comment]
update :) i found the genamons_rdkit executable!
maybe you can add this to the readme?


but i still have trouble with the cml module it is not installed correctly with ./install:

```
 genamon_rdkit -k 6 "ccccc"                                                                                              
/Users/jan/projects/aqml/cheminfo/rdkit/core.py:77: SyntaxWarning: invalid escape sequence '\ '
  """
/Users/jan/projects/aqml/cheminfo/rdkit/core.py:1053: SyntaxWarning: invalid escape sequence '\ '
  """
/Users/jan/projects/aqml/cheminfo/rdkit/core.py:1305: SyntaxWarning: invalid escape sequence '\C'
  print('    found bent C=C\C=C/C=C or alike, keep it!')
/Users/jan/projects/aqml/cheminfo/rdkit/core.py:2314: SyntaxWarning: invalid escape sequence '\i'
  """
/Users/jan/projects/aqml/cheminfo/rdkit/core.py:2387: SyntaxWarning: invalid escape sequence '\i'
  """
/Users/jan/projects/aqml/cheminfo/rdkit/core.py:2501: SyntaxWarning: invalid escape sequence '\ '
  """ get all non-covalent bonds (including both
/Users/jan/projects/aqml/cheminfo/rdkit/core.py:2599: SyntaxWarning: invalid escape sequence '\i'
  Todo = """_ncbs2 = []
Traceback (most recent call last):
  File "/Users/jan/projects/aqml/bin/genamon_rdkit", line 4, in <module>
    import aqml.cheminfo.algo.amon_mpi as coa2
  File "/Users/jan/projects/aqml/cheminfo/algo/amon_mpi.py", line 21, in <module>
    import cml.sd as dd
ModuleNotFoundError: No module named 'cml'
```

**Comment by binghuang2018** [comment]
> update :) i found the genamons_rdkit executable! maybe you can add this to the readme?
> 
> but i still have trouble with the cml module it is not installed correctly with ./install:
> 
> ```
>  genamon_rdkit -k 6 "ccccc"                                                                                              
> /Users/jan/projects/aqml/cheminfo/rdkit/core.py:77: SyntaxWarning: invalid escape sequence '\ '
>   """
> /Users/jan/projects/aqml/cheminfo/rdkit/core.py:1053: SyntaxWarning: invalid escape sequence '\ '
>   """
> /Users/jan/projects/aqml/cheminfo/rdkit/core.py:1305: SyntaxWarning: invalid escape sequence '\C'
>   print('    found bent C=C\C=C/C=C or alike, keep it!')
> /Users/jan/projects/aqml/cheminfo/rdkit/core.py:2314: SyntaxWarning: invalid escape sequence '\i'
>   """
> /Users/jan/projects/aqml/cheminfo/rdkit/core.py:2387: SyntaxWarning: invalid escape sequence '\i'
>   """
> /Users/jan/projects/aqml/cheminfo/rdkit/core.py:2501: SyntaxWarning: invalid escape sequence '\ '
>   """ get all non-covalent bonds (including both
> /Users/jan/projects/aqml/cheminfo/rdkit/core.py:2599: SyntaxWarning: invalid escape sequence '\i'
>   Todo = """_ncbs2 = []
> Traceback (most recent call last):
>   File "/Users/jan/projects/aqml/bin/genamon_rdkit", line 4, in <module>
>     import aqml.cheminfo.algo.amon_mpi as coa2
>   File "/Users/jan/projects/aqml/cheminfo/algo/amon_mpi.py", line 21, in <module>
>     import cml.sd as dd
> ModuleNotFoundError: No module named 'cml'
> ```

Hey Jan, sorry for the very ___late___ reply. I've been busy dealing with some tricky and urgent matters recently, so I haven't been able to reply to you in a timely manner. 

After a thorough check, I have two suggestions regarding this issue:

a) Review your error message for any compilation problems. There are Fortran codes that require gfortran for compilation, and if this fails, cml won't be installed successfully.

b) If the first suggestion doesn’t resolve the issue, modify the genamons_rdkit file so that it appears as follows:

```
func = coa.ParentMols 
#if ag.mpi:
#    func = coa2.ParentMols
```

I hope this helps!
